version: "3.7"

services:
  app:
    build: .
    restart: on-failure
    volumes:
      - ./:/home/app
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d/

volumes:
  mysql-data:
