version: '3.7'

services:
  springboot:
    build: .
    image: springboot
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - type: volume
        source: maven-repo
        target: /root/.m2
      - type: bind
        source: ./
        target: /home/app
    depends_on:
      - db

  db:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  maven-repo:
