version: "3.7"

services:
  flask:
    build: .
    restart: on-failure
    ports:
      - 5000:5000
    volumes:
      - ./:/home/app
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: on-failure
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
