version: "3.7"

services:
  app:
    restart: on-failure
    build: .
    ports:
      - 4000:4000
    links:
      - mongo

  mongo:
    image: mongo
    restart: on-failure
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-data: