version: '3.7'

services:
  springboot:
    build: .
    image: springboot
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - type: volume
        source: maven-repo
        target: /root/.m2
      - type: bind
        source: ./
        target: /home/app
    depends_on:
      - db

  db:
    image: postgres:11
    restart: on-failure
    environment:
      POSTGRES_DB: doploy
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d/

volumes:
  pg-data:
  maven-repo:
