version: "3.7"

services:
  app:
    restart: on-failure
    build: .
    volumes:
      - ./:/home/app
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    image: postgres:11
    restart: on-failure
    environment:
      POSTGRES_DB: doploy
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./
        target: /docker-entrypoint-initdb.d/

volumes:
  pg-data: