version: "3.7"

services:
  app:
    restart: on-failure
    build: .
    ports:
      - 4000:4000
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: on-failure
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: