version: '3.7'

services:
  springboot:
    build: .
    image: springboot
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - type: volume
        source: maven-repo
        target: /root/.m2
      - type: bind
        source: ./
        target: /home/app
    depends_on:
      - database

  database:
    image: mysql
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: container
      MYSQL_PASSWORD: container
      MYSQL_ROOT_PASSWORD: my-secret-pw
    restart: on-failure
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  maven-repo:
