# default active profile, see more in tool/start.sh
spring.profiles.active: dev

# general configuration
spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver

  # Show or not log for each sql query
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update

# swagger configuration
swagger:
  title: Doploy API Getaway
  api-version: 1.0.0
  license: MIT
  license-url: https://opensource.org/licenses/MIT
  contact:
    name: Alan, Zhufeng Xu
    homepage: https://www.alan-zhufengxu.com
    email: alan.xuzhufeng@gmail.com


---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/alansite?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: doploy
    password: doploy

server:
  port: 8090

spring.jpa.show-sql: true
springfox.documentation.swagger.v2.path: /api-docs