# default active profile, see more in tool/start.sh
spring.profiles.active: dev

# general configuration
spring:
  # Show or not log for each sql query
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update

# swagger configuration
swagger:
  title: HTTP API for SpringBoot Template
  api-version: 1.0.0
  description: This is the description for REST API
  license: MIT
  license-url: https://opensource.org/licenses/MIT
  contact:
    name: Alan, Zhufeng Xu
    homepage: https://www.alan-zhufengxu.com
    email: alan.xuzhufeng@gmail.com

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://test:test@db:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
      database: doploy

server:
  port: 8080

spring.jpa.show-sql: false
springfox.documentation.swagger.v2.path: /api-docs