version: "3.7"

services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./app/
        target: /home/app/
    depends_on:
      - db

  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432

volumes:
  pg-data: